export const SAVE_TODO_ITEM = "SAVE_TODO_ITEM";
export const CLEAR_COMPLETED = "CLEAR_COMPLETED";
export const TOGGLE_TODO_ITEM = "TOGGLE_TODO_ITEM";
export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";
